python train_mae_cifar10_jepa_cnn.py \
    --output_dir ../../autodl-tmp/output_jepa_cnn_sparse_in100/  \
    --img_size 32 \
    --patch_size 4 \
    --embed_dim 192 \
    --decoder_embed_dim 192 \
    --dataset 'imagenet100' \
    --data_path '../../autodl-fs/imagenet100' \
    --mask_ratio 0.75 \
    --num_views 1 \
    --encoder_type sparse_cnn \
    --decoder_type vit \
    --save_freq 20 
